baseURL = "https://aktech.github.io/hugo-react-nebari-demo/"
languageCode = "en-us"
title = "Nebari Design + Hugo"

disableKinds = ["taxonomy", "term", "RSS", "sitemap", "404"]

[build]
  writeStats = false
